require(deTestSet)

plot(andrews(),type="l",col="darkblue")
plot(beam(),type="l",col="darkblue")
plot(caraxis(),type="l",col="darkblue")
plot(crank(),type="l",col="darkblue")
plot(E5(),type="l",col="darkblue")
plot(emep(),type="l",col="darkblue")
plot(fekete(),type="l",col="darkblue")
plot(nand(),type="l",col="darkblue")
plot(orego(),type="l",col="darkblue")
plot(pollution(),type="l",col="darkblue")
plot(ring(),type="l",col="darkblue")
plot(rober(),type="l",col="darkblue")
plot(transistor(),type="l",col="darkblue")
plot(tube(),type="l",col="darkblue")
plot(twobit(),type="l",col="darkblue")
plot(wheelset(),type="l",col="darkblue")
